# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/let4be/pre-commit-rust
    rev: v1.0
    hooks:
        -   id: fmt
        -   id: clippy
-   repo: local
    hooks:
        -   id: generate-readme
            name: generate-readme
            entry: bash -c "markdown-pp README.tmpl.md -o README.md"
            language: system
            pass_filenames: false
