[profile.dev]
panic = "abort"
debug-assertions = false

[profile.release]
panic = "abort"
debug-assertions = false
opt-level = 3

[workspace]
    members = [
        "examples/find_duplicate_titles",
        "examples/simple",
        "examples/simple-short",
        "main"
    ]
