pre-release-replacements = [
    {file="README.tmpl.md", search="crusty-core = .*", replace="{{crate_name}} = \"~{{version}}\""},
    {file="src/config.rs", search="crusty-core/[^\"]*", replace="{{crate_name}}/{{version}}"},
]
